AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    hello-sam

    Sample SAM Template for hello-sam

Parameters:
  DomainName:
    Type: String
  HostedZoneId:
    Type: String

Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        HITS_TABLE_NAME: !Ref HitsTable

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.hello
      Runtime: nodejs8.10
      Policies:
        - AWSXrayWriteOnlyAccess
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:GetItem'
                - 'dynamodb:UpdateItem'
              Resource: !GetAtt HitsTable.Arn
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
  HealthcheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.health
      Runtime: nodejs8.10
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /health
            Method: get

  HitsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: HitsTable
      AttributeDefinitions:
        - AttributeName: ipAddress
          AttributeType: S
      KeySchema:
        - AttributeName: ipAddress
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS

  CustomDomain:
    Type: "AWS::ApiGateway::DomainName"
    Properties:
      RegionalCertificateArn: !Ref Certificate
      DomainName: !Ref DomainName
      EndpointConfiguration:
        Types:
          - REGIONAL

  Mapping:
    Type: "AWS::ApiGateway::BasePathMapping"
    Properties:
      DomainName: !Ref CustomDomain
      RestApiId: !Ref ServerlessRestApi
      Stage: Prod

  RegionalHealthcheck:
    Type: "AWS::Route53::HealthCheck"
    Properties:
      HealthCheckConfig:
        Port: "443"
        Type: "HTTPS"
        ResourcePath: "/Prod/health"
        FullyQualifiedDomainName: !Sub ${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com
        RequestInterval: "30"
        FailureThreshold: "1"
        Regions:
          - us-east-1
          - eu-west-1
          - ap-southeast-1
      HealthCheckTags:
        - Key: Name
          Value: !Sub hello-${AWS::Region}

  Record:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Name: !Ref DomainName
      Region: !Ref AWS::Region
      SetIdentifier: !Sub "${AWS::Region}-api"
      Type: A
      HostedZoneId: !Ref HostedZoneId
      HealthCheckId: !Ref RegionalHealthcheck
      AliasTarget:
        DNSName: !GetAtt CustomDomain.RegionalDomainName
        HostedZoneId: !GetAtt CustomDomain.RegionalHostedZoneId

Outputs:

  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn

  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn